version: '3.4'

services:
  api-one.api:
    image: api-one.api
    build:
      context: .
      dockerfile: Services/ApiOne/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "9010:80"
  api-two.api:
    image: api-two.api
    build:
      context: .
      dockerfile: Services/ApiTwo/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "9000:80"    