version: '3.4'

services:
  api-one:
    image: api-one
    build:
      context: .
      dockerfile: Services/ApiOne/Dockerfile
    ports:
      - 9010:80
    container_name: api-one
  api-two:
    image: api-two
    build:
      context: .
      dockerfile: Services/ApiTwo/Dockerfile
    environment:
      - UrlApiOneBase=http://api-one/
    ports:
      - 9000:80
    container_name: api-two
  app-softplan:
    image: app-softplan
    build: 
      context: .
      dockerfile: app-softplan/Dockerfile
    ports:
      - 3000:80
networks:    
  api-one:
    driver: bridge    
